apiVersion: batch/v1
kind: Job
metadata:
  name: todoapp-migrate
  namespace: todoapp
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: migrate/migrate:v4.19.1
          command:
            - sh
            - -c
          args:
            - migrate -path=/migrations -database="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@todoapp-postgres:5432/${POSTGRES_DB}?sslmode=disable" up
          envFrom:
            - secretRef:
                name: todoapp-secret
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: todoapp-migrations
